### ISSUE TITLE
unic-langid 0.5.3 breaks semver

### ISSUE THREAD

**Issue by distransient** [zbraniecki/unic-locale#18]
Moving types from the namespaces into the root is a semver breakage.

Please yank!

**Comment by zbraniecki** [comment]
thanks! yanking!

**Comment by zbraniecki** [comment]
I think I yanked all the broken revisions. I published them as 0.6.

Thank you again!

**Comment by Ratysz** [comment]
There seems to have been another breakage earlier, somewhere. Recent Amethyst revisions prior to amethyst/amethyst#1959 fail to compile with
```
Compiling amethyst_locale v0.7.0 (E:\Projects\amethyst\amethyst_locale)
error[E0277]: the trait bound `unic_langid_impl::LanguageIdentifier: std::convert::From<unic_langid_impl::LanguageIdentifier>` is not satisfied
  --> amethyst_locale\src\lib.rs:37:26
   |
37 |         let mut bundle = FluentBundle::new(&[lang_en]);
   |                          ^^^^^^^^^^^^^^^^^ the trait `std::convert::From<unic_langid_impl::LanguageIdentifier>` is not implemented for `unic_langid_impl::LanguageIdentifier`
   |
   = note: required because of the requirements on the impl of `std::convert::Into<unic_langid_impl::LanguageIdentifier>` for `unic_langid_impl::LanguageIdentifier`
   = note: required by `fluent_bundle::bundle::FluentBundle::<R>::new`

error: aborting due to previous error
```

**Comment by zbraniecki** [comment]
@Ratysz - I hope that yanking fixes that. Does it not?

**Comment by distransient** [comment]
Thanks for the quick response!

**Comment by Ratysz** [comment]
This log is from trying it like two minutes ago, after `cargo clean` and `cargo update`, so I think yanking 0.5.3 didn't fix this (it did fix revisions after the linked PR, though).

**Comment by zbraniecki** [comment]
I tested on local master:

```
cd amethyst_locale
cargo clean
cargo update
cargo build
cargo test
```

and it works. Not sure how to test it further?

**Comment by Ratysz** [comment]
The problem is with earlier revisions. `amethyst_locale` 0.7.1 compiles just fine, thanks to your swift action; `anethyst_locale` 0.7.0 (fresh, of course) doesn't compile anymore, failing with the error I pasted. (This crops up while I'm trying to compare different revisions of Amethyst to find out if there was a regression in `amethyst_tiles`; I might be doing it wrong, though.)

**Comment by zbraniecki** [comment]
ah, hmm, I think it must be some misalignment between fluent-locale and fluent-bundle. I'll update both to use unic-langid 0.6 soon.

**Comment by zbraniecki** [comment]
ok, yanked `fluent-bundle` and `fluent` 0.7.2. It should make both use 0.7.1 which uses 0.4

**Comment by zbraniecki** [comment]
ugh, but that broke master :(

**Comment by Ratysz** [comment]
Fixed the revisions I'm interested in, though; thank you!

**Comment by zbraniecki** [comment]
no worries! updating all the crates :)

**Comment by zbraniecki** [comment]
ok got all crates updated - `unic-langid` to 0.6, `fluent-locale` to 0.10 and `fluent` to 0.8.

We may need to yank amethyst_locale 0.7.1 and push 0.7.2 updated to those revisions!
